### ISSUE TITLE
Static homepage

### ISSUE THREAD

**Issue by LittleHamster** [ryanwiemer/rw#6]
@ryanwiemer 
thanks for sharing the code for your amazing portfolio :)

I want to achieve something similar using the starter template
the issue here: 
https://github.com/ryanwiemer/gatsby-starter-gcn/issues/72

so in this example, you have a home page which lists the portfolio and a separate page for the blogs, can the same method be used in the starter theme?

**Comment by LittleHamster** [comment]
@ryanwiemer any feedback about this?

**Comment by ryanwiemer** [comment]
@LittleHamster sorry I have been a little busy. 

I'm happy to answer this question but it might be best to move it over to [Stackoverflow](https://stackoverflow.com/) or [Spectrum](https://spectrum.chat/gatsby-js?tab=posts) as that is more of a generic question rather than something specific to this repo.
